<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net5.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <!-- Target olders runtime -->
        <!-- We also need "rollForward": "Major", defined in runtimeconfig.json in this repo -->
        <CheckEolTargetFramework>false</CheckEolTargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Avalonia.BuildServices.Protocol/Avalonia.BuildServices.Protocol.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Compile Include="../Avalonia.BuildServices/Logger.cs" Link="Logger.cs" />
    </ItemGroup>
</Project>
