name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x

    - name: Run Nuke
      run: dotnet run --project build/_build.csproj

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Nuget package
        path: ./artifacts/packages/*.nupkg
